version: '3.1'

services:
  wtwtb-db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'dev_wtwtb_db'
      MYSQL_USER: 'dev_wtwtb_db_user'
      MYSQL_PASSWORD: 'dev_wtwtb_db_password'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'