version: '3.1'

services:
  wtwtb-bot:
    build:
      context: .
    depends_on:
      - wtwtb-db
    environment:
      BOT_USERNAME: ${BOT_USERNAME}
      BOT_TOKEN: ${BOT_TOKEN}
      API_KEY: ${API_KEY}
      SPRING_DATASOURCE_URL: 'jdbc:mysql://host.docker.internal:3306/wtwtb_db'
      SPRING_DATASOURCE_USERNAME: ${BOT_DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${BOT_DB_PASSWORD}
      SPRING_JPA_DATABASE-PLATFORM: 'org.hibernate.dialect.MySQL5InnoDBDialect'
      SPRING_FLYWAY_SCHEMAS: 'wtwtb_db'
      SPRING_FLYWAY_ENABLED: 'true'
    restart: always
  wtwtb-db:
    image: mysql:5.7
    environment:
      MYSQL_USER: ${BOT_DB_USERNAME}
      MYSQL_PASSWORD: ${BOT_DB_PASSWORD}
      MYSQL_DATABASE: 'wtwtb_db'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'